<#
	Script used to run selected subscriptions through the data collection script for any sub
	identified in teh input file $in
	
	$in will have been generated by _CMP01_CollectSubs.ps1 and then further modified 
	to include only the subscriptions to review. 
	
	Those subscriptions will then be processed with _CMP03_Check.ps1
#>

#####################################################
# Parameters for the script
# out - File name to output subs, path fixed internally
#####################################################
param(
	[string]$in
)

$subList = (Get-Content -Path ('.\' + $in) -raw) | ConvertFrom-Json

foreach($sub in $subList.PSObject.Properties)
{
	Write-Host("Name: " + $sub.Name)
	Write-Host("ID: " + $sub.Value)
	#.\_CMP03_Check.ps1 -subId $sub.Value -subName $sub.Name
	.\_CMP04_IsolatedDelete.ps1 -subId $sub.Value -subName $sub.Name -rgPattern 'saw'
}
